# Generated by Django 2.2.6 on 2023-08-14 16:34

import apps_other.app_bot.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('introduction', models.TextField(blank=True, max_length=255, null=True)),
                ('creatUser', models.CharField(max_length=255)),
                ('creatDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[apps_other.app_bot.models.validate_utter_field])),
                ('example', django_mysql.models.JSONField(default=list, help_text='列表格式', null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bot.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('story_type', models.CharField(max_length=50)),
                ('example', django_mysql.models.JSONField(default=list, help_text='列表格式', null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bot.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[apps_other.app_bot.models.validate_english])),
                ('example', django_mysql.models.JSONField(default=list, help_text='列表格式', null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bot.Bot')),
            ],
        ),
    ]
