# Generated by Django 2.2.6 on 2023-09-08 15:28

import apps_other.app_bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utterance',
            name='example',
            field=models.TextField(default=list, help_text='列表格式', null=True, verbose_name='样例'),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='name',
            field=models.CharField(max_length=50, validators=[apps_other.app_bot.models.validate_utter_field], verbose_name='响应名字'),
        ),
    ]
