# Generated by Django 2.2.6 on 2021-06-28 15:01

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operator", models.CharField(db_index=True, max_length=20, null=True)),
                (
                    "operate_type",
                    models.CharField(
                        choices=[("add", "新增"), ("modify", "修改"), ("exec", "执行"), ("delete", "删除")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="添加时间")),
                ("operate_obj", models.CharField(db_index=True, default="", max_length=50)),
                ("operate_summary", models.TextField(default="")),
            ],
            options={
                "verbose_name": "使用记录",
            },
        ),
        migrations.CreateModel(
            name="SysSetting",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("key", models.CharField(max_length=100, unique=True, verbose_name="设置项")),
                ("value", models.TextField(verbose_name="设置值")),
                ("desc", models.CharField(default="", max_length=200, verbose_name="设置描述")),
            ],
            options={
                "verbose_name": "系统设置",
            },
        ),
        migrations.CreateModel(
            name="SysUser",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("bk_username", models.CharField(max_length=50, unique=True, verbose_name="用户名称")),
                (
                    "role",
                    models.SmallIntegerField(
                        choices=[(0, "超级管理员"), (1, "运维管理员"), (2, "应用管理员"), (3, "普通用户")], default=3, verbose_name="用户角色"
                    ),
                ),
                ("phone", models.CharField(default="", max_length=20, verbose_name="电话号码")),
                ("email", models.CharField(default="", max_length=100, verbose_name="邮箱地址")),
                ("chname", models.CharField(default="", max_length=50, verbose_name="中文名称")),
                ("biz_ids", django_mysql.models.JSONField(default=dict, verbose_name="系统关注业务ID列表(对应CMDB业务ID)")),
            ],
            options={
                "verbose_name": "系统用户",
            },
        ),
    ]
