# Generated by Django 2.2.6 on 2021-07-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sysuser",
            name="wx_userid",
            field=models.CharField(default="", max_length=200, verbose_name="微信openId"),
        ),
    ]
