# Generated by Django 2.2.6 on 2021-10-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0002_sysuser_wx_useid"),
    ]

    operations = [
        migrations.AddField(
            model_name="syssetting",
            name="vtype",
            field=models.CharField(default="string", max_length=32, verbose_name="类型"),
        ),
        migrations.CreateModel(
            name="UserSysSetting",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("vtype", models.CharField(default="string", max_length=32, verbose_name="类型")),
                ("key", models.CharField(max_length=100, verbose_name="key值")),
                ("value", models.TextField(default="", verbose_name="系统设置值")),
                ("desc", models.TextField(blank=True, verbose_name="描述")),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="system_mgmt.SysUser"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户系统设置",
            },
        ),
    ]
