# Generated by Django 2.2.6 on 2021-11-19 10:52

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0003_auto_20211014_1640"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeManager",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("grade_manager_id", models.IntegerField(default=0, help_text="分级管理员id", unique=True)),
                ("version", models.CharField(default="v1", help_text="版本", max_length=50)),
                ("policies", django_mysql.models.JSONField(default=dict, help_text="权限数据")),
            ],
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.SmallIntegerField(
                        choices=[(3, "普通用户"), (2, "应用管理员"), (1, "运维管理员"), (0, "超级管理员")], help_text="对应的系统角色"
                    ),
                ),
                ("group_id", models.IntegerField(default=0, help_text="用户组id", unique=True)),
                ("group_name", models.CharField(default="", help_text="用户组name", max_length=200)),
                ("version", models.CharField(default="v1", help_text="版本", max_length=50)),
                ("policies", django_mysql.models.JSONField(default=dict, help_text="权限数据")),
                ("is_used", models.BooleanField(default=False, help_text="当前使用的版本")),
            ],
        ),
    ]
