# Generated by Django 2.2.6 on 2022-02-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0005_grademanager_is_used"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GradeManager",
        ),
        migrations.DeleteModel(
            name="UserGroup",
        ),
    ]
