# Generated by Django 2.2.6 on 2022-02-14 10:12

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0006_auto_20220210_1336"),
    ]

    operations = [
        migrations.CreateModel(
            name="SysRole",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("role_name", models.CharField(max_length=128, unique=True, verbose_name="角色名称")),
                ("describe", models.CharField(default="", max_length=256, verbose_name="角色描述")),
            ],
            options={
                "verbose_name": "系统角色",
            },
        ),
        migrations.RemoveField(
            model_name="sysuser",
            name="biz_ids",
        ),
        migrations.RemoveField(
            model_name="sysuser",
            name="role",
        ),
        migrations.AddField(
            model_name="sysuser",
            name="bk_user_id",
            field=models.SmallIntegerField(default=0, verbose_name="用户id(用户管理处的id)"),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="bk_username",
            field=models.CharField(max_length=128, unique=True, verbose_name="用户名称"),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="chname",
            field=models.CharField(default="", max_length=128, verbose_name="中文名称"),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="email",
            field=models.CharField(max_length=100, verbose_name="邮箱地址"),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="电话号码"),
        ),
        migrations.CreateModel(
            name="SysApps",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("app_name", models.CharField(max_length=128, verbose_name="资源名称")),
                ("app_key", models.CharField(max_length=64, verbose_name="资源标识")),
                ("app_ids", django_mysql.models.JSONField(default=dict, verbose_name="资源列表")),
                ("sys_role", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="system_mgmt.SysRole")),
            ],
            options={
                "verbose_name": "角色资源",
            },
        ),
        migrations.AddField(
            model_name="sysuser",
            name="roles",
            field=models.ManyToManyField(to="system_mgmt.SysRole", verbose_name="角色"),
        ),
    ]
