# Generated by Django 2.2.6 on 2022-02-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0007_auto_20220214_1012"),
    ]

    operations = [
        migrations.AddField(
            model_name="sysrole",
            name="built_in",
            field=models.BooleanField(default=False, verbose_name="是否内置(内置不允许修改)"),
        ),
    ]
