# Generated by Django 2.2.6 on 2022-02-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0008_sysrole_built_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="sysuser",
            name="sexuality",
            field=models.PositiveSmallIntegerField(choices=[(0, "男"), (1, "女")], default=0, verbose_name="性别"),
        ),
    ]
