# Generated by Django 2.2.6 on 2022-03-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0009_sysuser_sexuality"),
    ]

    operations = [
        migrations.AddField(
            model_name="sysuser",
            name="local",
            field=models.BooleanField(default=True, verbose_name="是否为默认目录用户"),
        ),
        migrations.AlterField(
            model_name="sysrole",
            name="describe",
            field=models.CharField(blank=True, default="", max_length=256, null=True, verbose_name="角色描述"),
        ),
    ]
