# Generated by Django 2.2.6 on 2022-06-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0010_auto_20220301_1457"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationlog",
            name="current_ip",
            field=models.CharField(db_index=True, default="127.0.0.1", max_length=50),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="app_module",
            field=models.CharField(db_index=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="obj_type",
            field=models.CharField(db_index=True, default="", max_length=30),
        ),
    ]
