# Generated by Django 2.2.6 on 2022-06-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0011_operationlog_current_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationlog",
            name="operate_obj",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="operate_type",
            field=models.CharField(
                choices=[("add", "新增"), ("modify", "修改"), ("exec", "执行"), ("delete", "删除"), ("download", "下载")],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
