# Generated by Django 2.2.6 on 2022-07-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0012_auto_20220617_1011"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationlog",
            name="operator",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
