# Generated by Django 2.2.6 on 2022-10-12 14:43

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0014_auto_20220804_0957"),
    ]

    operations = [
        migrations.AddField(
            model_name="sysuser",
            name="departments",
            field=django_mysql.models.JSONField(default=list, verbose_name="组织架构"),
        ),
        migrations.AddField(
            model_name="sysuser",
            name="leader",
            field=django_mysql.models.JSONField(default=list, verbose_name="上级"),
        ),
    ]
