# Generated by Django 2.2.6 on 2023-04-28 13:59

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0016_auto_20230129_1038"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuManage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("menu_name", models.CharField(help_text="菜单名称", max_length=64, unique=True)),
                ("default", models.BooleanField(default=False, help_text="是否是内置菜单")),
                ("use", models.BooleanField(default=False, help_text="是否启用(只能有一个)")),
                ("menu", django_mysql.models.JSONField(default=dict, help_text="菜单内容")),
            ],
            options={
                "verbose_name": "菜单管理",
            },
        ),
    ]
