# Generated by Django 2.2.6 on 2023-07-19 16:03

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0018_sysuser_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstancesPermissions",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("instance_type", models.CharField(help_text="实例类型", max_length=64)),
                ("permissions", django_mysql.models.JSONField(default=dict, help_text="权限类型")),
                ("instances", django_mysql.models.JSONField(default=list, help_text="实例id")),
                ("role", models.ForeignKey(on_delete=True, to="system_mgmt.SysRole")),
            ],
            options={
                "verbose_name": "时间相关字段",
                "abstract": False,
            },
        ),
    ]
