# Generated by Django 2.2.6 on 2023-09-12 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0019_instancespermissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instancespermissions",
            name="role",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="system_mgmt.SysRole"),
        ),
    ]
