# Generated by Django 2.2.6 on 2022-09-19 14:04

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("registration_code", models.CharField(max_length=100, verbose_name="注册码")),
                ("activation_code", models.CharField(max_length=1024, verbose_name="激活码")),
                ("start_date", models.CharField(max_length=100, verbose_name="起始时间")),
                ("expiration_date", models.CharField(max_length=100, verbose_name="结束时间")),
                ("activation_status", models.CharField(max_length=100, verbose_name="激活状态")),
                ("agent_num", models.IntegerField(default=0, verbose_name="节点数")),
                ("applications", django_mysql.models.JSONField(default=list, verbose_name="功能模块")),
                ("notify_day", models.IntegerField(default=30, verbose_name="到期提醒")),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="创建时间")),
                ("desc", models.TextField(blank=True, null=True, verbose_name="描述")),
            ],
        ),
    ]
