# Generated by Django 2.2.6 on 2022-04-11 17:24

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("system_mgmt", "0010_auto_20220301_1457"),
    ]

    operations = [
        migrations.CreateModel(
            name="Labels",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, help_text="使用时间")),
                ("deleted_at", models.DateTimeField(auto_now=True, help_text="取消时间")),
            ],
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("title", models.CharField(help_text="文章标题", max_length=255)),
                ("content", models.TextField(help_text="文章内容")),
                ("body", django_mysql.models.JSONField(default="{}", help_text="文章完整内容")),
            ],
            options={
                "verbose_name": "文章",
            },
        ),
        migrations.CreateModel(
            name="RepositoryLabels",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("label_name", models.CharField(help_text="标签名称", max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "标签",
            },
        ),
        migrations.CreateModel(
            name="RepositoryTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="更新者")),
                ("template_name", models.CharField(help_text="模版内容", max_length=64, unique=True)),
                ("template_img", models.TextField(default="", help_text="图标base64")),
                ("template", django_mysql.models.JSONField(default=dict, help_text="模版内容")),
                ("labels", models.ManyToManyField(help_text="标签", to="repository.RepositoryLabels")),
            ],
            options={
                "verbose_name": "模版",
            },
        ),
        migrations.CreateModel(
            name="RepositoryCollectUser",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, help_text="收藏时间")),
                ("deleted_at", models.DateTimeField(auto_now=True, help_text="取消收藏时间")),
                (
                    "repository",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="repository.Repository"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="system_mgmt.SysUser")),
            ],
        ),
        migrations.AddField(
            model_name="repository",
            name="collect_users",
            field=models.ManyToManyField(
                help_text="收藏用户",
                related_name="collect_users",
                through="repository.RepositoryCollectUser",
                to="system_mgmt.SysUser",
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="create_user",
            field=models.ForeignKey(
                help_text="作者",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="create_user",
                to="system_mgmt.SysUser",
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="labels",
            field=models.ManyToManyField(
                help_text="标签",
                related_name="repository_labels",
                through="repository.Labels",
                to="repository.RepositoryLabels",
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="template",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="repository.RepositoryTemplate"),
        ),
        migrations.AddField(
            model_name="labels",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repository_labels",
                to="repository.Repository",
            ),
        ),
        migrations.AddField(
            model_name="labels",
            name="repository_labels",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="repository.RepositoryLabels"),
        ),
    ]
