# Generated by Django 2.2.6 on 2022-04-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0002_auto_20220412_1804"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="create_user",
        ),
        migrations.AddField(
            model_name="repository",
            name="created_by",
            field=models.CharField(default="", max_length=32, verbose_name="创建者"),
        ),
        migrations.AddField(
            model_name="repository",
            name="updated_by",
            field=models.CharField(default="", max_length=32, verbose_name="更新者"),
        ),
    ]
