# Generated by Django 2.2.6 on 2022-04-15 18:08

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0003_auto_20220414_1545"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="body",
            field=django_mysql.models.JSONField(default="[]", help_text="文章完整内容"),
        ),
    ]
