# Generated by Django 2.2.6 on 2022-04-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0004_auto_20220415_1808"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorytemplate",
            name="template_repository_name",
            field=models.CharField(default="", help_text="模版文章名称", max_length=255),
        ),
    ]
