# Generated by Django 2.2.6 on 2022-04-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0005_repositorytemplate_template_repository_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="body",
            field=models.TextField(default="[]", help_text="文章完整内容"),
        ),
    ]
