# Generated by Django 2.2.6 on 2022-05-16 15:37

from django.db import migrations, models
import django_minio_backend.models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0006_auto_20220422_1117"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="images",
            field=django_mysql.models.JSONField(default="[]", help_text="文件名称列表"),
        ),
        migrations.AlterField(
            model_name="repositorytemplate",
            name="template_img",
            field=models.FileField(
                blank=True,
                help_text="模版图片",
                null=True,
                storage=django_minio_backend.models.MinioBackend(bucket_name="weops-repository-private"),
                upload_to="template",
            ),
        ),
    ]
