# Generated by Django 2.2.6 on 2022-05-19 17:25

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0007_auto_20220516_1537"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorytemplate",
            name="images",
            field=django_mysql.models.JSONField(default="{}", help_text="文件名称列表"),
        ),
        migrations.AlterField(
            model_name="repository",
            name="images",
            field=django_mysql.models.JSONField(default="{}", help_text="文件名称列表"),
        ),
    ]
