# Generated by Django 2.2.6 on 2022-05-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0008_auto_20220519_1725"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repositorytemplate",
            name="template_repository_name",
            field=models.CharField(blank=True, default="", help_text="模版文章名称", max_length=255, null=True),
        ),
    ]
