# Generated by Django 2.2.6 on 2022-06-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0009_auto_20220525_1650"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="is_it_service",
            field=models.BooleanField(default=False, help_text="是否为IT服务台文章"),
        ),
    ]
