# Generated by Django 2.2.6 on 2022-08-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0010_repository_is_it_service"),
    ]

    operations = [
        migrations.RenameField(
            model_name="repositorytemplate",
            old_name="template",
            new_name="body",
        ),
        migrations.RenameField(
            model_name="repositorytemplate",
            old_name="template_repository_name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="repository",
            name="base_id",
            field=models.IntegerField(default=0, help_text="草稿原文id"),
        ),
        migrations.AddField(
            model_name="repository",
            name="drafts",
            field=models.BooleanField(default=False, help_text="是否为草稿"),
        ),
        migrations.AlterField(
            model_name="repositorytemplate",
            name="template_img",
            field=models.CharField(blank=True, help_text="模版图片", max_length=100, null=True),
        ),
    ]
